"""Terminal status codes for WISE per §31.8."""

from __future__ import annotations

VERIFIED = "VERIFIED"
TAMPERED = "TAMPERED"
INVALID_PROOF = "INVALID_PROOF"
UNREADABLE_ARTIFACT = "UNREADABLE_ARTIFACT"
UNSUPPORTED_ALGORITHM = "UNSUPPORTED_ALGORITHM"
USER_ERROR = "USER_ERROR"

EXIT_CODES = {
    VERIFIED: 0,
    TAMPERED: 1,
    INVALID_PROOF: 2,
    UNREADABLE_ARTIFACT: 3,
    UNSUPPORTED_ALGORITHM: 4,
    USER_ERROR: 5,
}
